//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gv1WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoan()
        {
            this.tblUserLoan = new HashSet<tblUserLoan>();
        }
    
        public int tblLoanId { get; set; }
        public int ActualLoanId { get; set; }
        public int PrimaryBorrowerId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public int tblLoanStatusId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblLoanStatus tblLoanStatus { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLoan> tblUserLoan { get; set; }
    }
}
