//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gv1WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int tblSettingId { get; set; }
        public int tblUserId { get; set; }
        public bool IsAllSettingsEnabled { get; set; }
        public bool IsPushNotificationsEnabled { get; set; }
        public bool IsAlertsEnabled { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
