//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalInfo
    {
        public int Id { get; set; }
        public Nullable<int> YOS { get; set; }
        public Nullable<int> percentage { get; set; }
        public Nullable<int> backlogs { get; set; }
        public string Specialization { get; set; }
        public string College { get; set; }
    
        public virtual studentInfo studentInfo { get; set; }
    }
}
